# Copyright (c) Codesphere Inc.
# SPDX-License-Identifier: Apache-2.0

name: Tag

on:
  push:
    branches:
      - main

jobs:
  integration-tests:
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit

  tag:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: 'go.mod'

      - name: Tag
        run: hack/tag-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign in to Google Cloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        if: env.RELEASE_VERSION != ''
        with:
          credentials_json: ${{ secrets.GOOGLE_BUCKET_CREDS_JSON }}

      - name: Upload archive to Google Bucket
        uses: 'google-github-actions/upload-cloud-storage@6397bd7208e18d13ba2619ee21b9873edc94427a' # v3
        if: env.RELEASE_VERSION != ''
        with:
          path: dist
          glob: '*.tar.gz'
          parent: false
          destination: 'codesphere-oms-builds/tag/oms-${{ env.RELEASE_VERSION }}/${{ env.FOLDER }}'
